### ISSUE TITLE
Failed login creates blank screen

### ISSUE THREAD

**Issue by WeetLee** [Diplow/TheBigPicture#67]
https://github.com/Diplow/TheBigPicture/blob/6f8616d8c94c60a8a255e92a3f84af209fff52e0/front/app/actions/api.js#L297

If a user uses bad credentials, the popin of autentication failed is correctly displayed. However, the process keep going and
>     localStorage.setItem('user', JSON.stringify(json.user));
stores the string value "undefined". In js this value is different from undefined. Thus the parsing issue on app>reducers>requets.js#L64

**Comment by Diplow** [comment]
will do, thanks!
